***1 Завдання***

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 1, 1], [0.05, 0.07, 0], [0.05, 0, 0.06]])
a

array([[1.  , 1.  , 1.  ],
       [0.05, 0.07, 0.  ],
       [0.05, 0.  , 0.06]])

In [3]:
b = np.array([50000, 2250, 1400])
b

array([50000,  2250,  1400])

In [4]:
result = np.linalg.solve(a, b)
result

array([10000., 25000., 15000.])

***2 Завдання***

In [8]:
a = np.array([[1, 1, 1], [1, -1, 0], [1, 0, -1]])
a

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [ 1,  0, -1]])

In [9]:
b = np.array([1328, -120, 100])
b

array([1328, -120,  100])

In [17]:
result = np.linalg.solve(a, b)
result

array([436., 556., 336.])

***3 Завдання***

In [18]:
a = np.array([[3, 0, 3], [6, 1/4, 0], [1, 1/3, 1]])
a

array([[3.        , 0.        , 3.        ],
       [6.        , 0.25      , 0.        ],
       [1.        , 0.33333333, 1.        ]])

In [19]:
b = np.array([1, 1, 1])
b

array([1, 1, 1])

In [20]:
result = np.linalg.solve(a, b)
result

array([0.08333333, 2.        , 0.25      ])

In [48]:
result_true = (1/result)**0.5
result_true

array([0.5       , 0.4472136 , 0.57735027])

***4 Завдання***

In [49]:
a = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])
a

array([[ 1,  1,  1],
       [ 9,  3,  1],
       [ 1, -1,  1]])

In [50]:
b = np.array([12, 54, 2])
b

array([12, 54,  2])

In [51]:
result = np.linalg.solve(a, b)
result

array([4., 5., 3.])

***5 Завдання***

In [52]:
def get_polynom(coords):
    a = []
    b = []
    for x, y in coords:
        b.append(y)
        c = []
        for i in range(len(coords)):
            c.append(x ** i)
        a.append(c)
    return np.linalg.solve(a, b)

In [53]:
get_polynom([(1, 7), (2, 5), (3, 6)])

array([12. , -6.5,  1.5])